admin_zoo_fototek_bases_routes:
    resource: "@AdminZooFototekBundle/Resources/config/routing/bases.yml"
    prefix:     /phototheque

admin_zoo_fototek_image_routes:
    resource: "@AdminZooFototekBundle/Resources/config/routing/image.yml"
    prefix:     /phototheque/images

admin_zoo_fototek_category_routes:
    resource: "@AdminZooFototekBundle/Resources/config/routing/category.yml"
    prefix:     /phototheque/categories
